### PR TITLE
Added PathSegmentsAwareInterface

### PR DESCRIPTION
**Pull request by XedinUnknown**
The new `PathSegmentsAwareInterface` exposes segments of the path, as opposed to just the whole path string. The `PathAwareInterface` is now `PathSegmentsAware`.

### CODE REVIEW

**Review by mecha — COMMENTED** [review]
Intuitively I would imagine that `PathSegmentsAwareInterface` would extend `PathAwareInterface`, not the other way around.

My reasoning being that if an implementation can provide a path, it does not need to be burdened with also providing the segments, which may require string or array manipulations.

On the other hand, if an implementation is to be able to provide segments, then it makes sense for it to be expected to also provide the full path. Creating a path from segments is easier and the implementation might already have the path (for instance if the path was given during construction).

**Comment by XedinUnknown** [comment]
@mecha, my reasoning was as follows.

If something can provide a path, it also knows the segments of that path. On the other hand, conversion of segments into a path requires the implementation to know of the segment separator, which may be unknown, or irrelevant.

**Comment by mecha** [comment]
> If something can provide a path, it also knows the segments of that path.

Is that really the case? I would disagree simply because an object might only know about a path, without any knowledge of segments, separators, length, etc. I think having `PathAwareInterface` be also `PathSegmentsAwareInterface` is too much.

> On the other hand, conversion of segments into a path requires the implementation to know of the segment separator ...

That's a good point; I agree. Though the same may be said if `PathAwareInterface` is also `PathSegmentsAwareInterface`. Knowing the path does not imply knowing the segments, and vice versa. For that, the implementation would have to know how to split the path or join the segments, both requiring (as you said) knowledge of the separator.

If I may be permitted to change my opinion, I think `PathSegmentsAwareInterface` be `PathAwareInterface` is also too much. Perhaps the two interface ought to exist agnostic of each other. Of course, there will be cases were both paths and segments are required, so a third interface may be added that unifies them. Thoughts?

**Comment by mecha** [comment]
**Proposition:**

Keep the interfaces separate, but change `PathAwareInterface#getPath()` such that it is also able to return a `StringableInterface` instance. This would allow us to write an object implementation for something that represents a **path**.

_Example:_  
```php
<?php

class FilePath implements StringableInterface, PathSegmentsAwareInterface
{
}
```

The path object itself can provide the segments and can also be used as a string, thus making it a valid return type for `PathAwareInterface#getPath()`.

**Comment by XedinUnknown** [comment]
I agree that the interfaces don't have to extend one another, and that perhaps a third interface could be practical. Right now, I don't see a conceptual need for the third interface, however, and I'm struggling, as always, to come up with a name for it.

I also agree that `PathAwareInterface` should be allowed to return a `StringableInterface`, and that implementations MAY make that object path-segments-aware.

**Comment by mecha** [comment]
I also can't see a need for a third interface, to be honest. Perhaps it's worth tackling this when, and if, a need arises.

**Review by mecha — APPROVED** [review]

**Pull request merged**
